language: node_js
node_js:
  - "9"
before_script: chmod 0777 ./node_modules/.bin/mocha
 notifications:
    slack: 
      rooms:
        wksp-s2-epsi-oss-b3:MFi7kjnrnghncYqu58vRGTwE#equipe-jagermeicode