language: node_js
node_js:
  - "9"
env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - node_modules
before_install:
  - node-pre-gyp install --fallback-to-build
  - npm prune
before_script: chmod 0777 ./node_modules/.bin/mocha
notifications:
    slack: wksp-s2-epsi-oss-b3:MFi7kjnrnghncYqu58vRGTwE
